--- 
- name: create mTLS policy   
  command: oc   apply -f {{ role_path }}/files/mTLS-policy.yaml -n bookinfo  

- name: create destination rules
  command: oc   apply -f {{ role_path }}/files/destination-rules.yaml -n bookinfo 

- name: process gateway and service template
  template:
    src: productpage-gateway.yaml.j2
    dest: "/tmp/productpage-gateway-{{ cluster.name }}.yaml"
  vars:
    namespace: bookinfo

- name: create gateway and service config
  command: oc   apply -f /tmp/productpage-gateway-{{ cluster.name }}.yaml -n bookinfo      